[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'FRAME pallet template for defining custom runtime logic.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'sp-mvm'
repository = 'https://github.com/substrate-developer-hub/substrate-mv-node/'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']


[dependencies.log]
version = "0.4"
default-features = false

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.move-vm]
package = "dvm"
git = "https://github.com/dfinance/sp-move-vm.git"
branch = "master"
default-features = false


[dependencies]
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }


# Move, addition deps for addrs & results:
move-vm-runtime = { git = "https://github.com/dfinance/sp-move-vm.git", branch = "master", default-features = false }
move-core-types = { git = "https://github.com/dfinance/sp-move-vm.git", branch = "master", default-features = false }
move-vm-types = { git = "https://github.com/dfinance/sp-move-vm.git", branch = "master", default-features = false }

# corelib, std, structs:
sp-std = { default-features = false, version = '2.0.0' }
sp-core = { default-features = false, version = '2.0.0' }
# for logging, `sp_runtime::print`:
sp-runtime = { default-features = false, version = '2.0.0' }
# sp-io = { default-features = false, version = '2.0.0' }


[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }


[features]
default = ['std']
std = [
    "log/std",
    'move-vm/std',
    "move-vm-runtime/std",
    'move-core-types/std',
    # "sp-io/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    'codec/std',
    'frame-support/std',
    'frame-system/std',
]
