[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'mv-node'
repository = 'https://github.com/substrate-developer-hub/substrate-mv-node/'
version = '3.0.0'

[[bin]]
name = 'mv-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }

[dependencies]
jsonrpc-core = '15.1.0'
serde_json = '1.0'
structopt = '0.3.8'
codec = { package = 'parity-scale-codec', version = '2.0.0' }
log = "0.4"
serde = { version = "1.0", features = ["derive"]}

# Substrate dependencies
frame-benchmarking = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
frame-benchmarking-cli = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
pallet-transaction-payment-rpc = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
substrate-frame-rpc-system = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
substrate-prometheus-endpoint = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }

# Substarte Client Dependencies
sc-basic-authorship = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-cli = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', features = ['wasmtime'] }
sc-client-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-consensus = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-consensus-aura = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-executor = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', features = ['wasmtime'] }
sc-finality-grandpa = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-keystore = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-rpc = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-rpc-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-service = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', features = ['wasmtime'] }
sc-telemetry = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-transaction-pool = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-tracing = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-chain-spec = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sc-network = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }

# Substrate Primitive Dependencies
sp-api = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-block-builder = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-blockchain = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-consensus = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-consensus-aura = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-core = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-finality-grandpa = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-inherents = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-runtime = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-transaction-pool = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-timestamp = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-session = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-offchain = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }
sp-keystore = { git = 'http://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8' }

# Cumulus dependencies
cumulus-client-consensus-aura = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }
cumulus-client-consensus-common = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }
cumulus-client-network = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }
cumulus-client-service = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }
cumulus-client-cli = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }
cumulus-primitives-core = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }
cumulus-primitives-parachain-inherent = { git = 'http://github.com/paritytech/cumulus.git', branch = 'polkadot-v0.9.8' }

# Polkadot dependencies
polkadot-primitives = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.8' }
polkadot-service = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.8' }
polkadot-parachain = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.8' }

# Local dependencies
mv-node-runtime = { path = '../runtime' }
sp-mvm-rpc = { path = '../pallets/sp-mvm/rpc' }
sp-mvm-rpc-runtime = { path = '../pallets/sp-mvm/rpc/runtime' }

# FIXME: You MUST set the relay chain networks you wish to target in the `features` here
# Options are found here: https://github.com/paritytech/polkadot/blob/master/cli/Cargo.toml#L64-L71
#
# Alternatively to setting here, you can use cargo CLI at build time:
# https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options  
#
# ** Don't enable relay chains you don't need, as this is a **very** heavy build for no reason**
# More info: https://github.com/paritytech/polkadot/pull/3189
polkadot-cli = { git = 'http://github.com/paritytech/polkadot.git', branch = 'release-v0.9.8', features = ["rococo-native"] }

[features]
default = []
runtime-benchmarks = ['mv-node-runtime/runtime-benchmarks', 'polkadot-service/runtime-benchmarks']
