[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
build = 'build.rs'
description = 'A fresh FRAME-based Substrate node, ready for hacking.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'mv-node'
repository = 'https://github.com/substrate-developer-hub/substrate-mv-node/'
version = '3.0.0'

[[bin]]
name = 'mv-node'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = '3.0.0'
stdlib-fetch = { path = "../utils/stdlib-fetch" }

[dependencies]
jsonrpc-core = '15.1.0'
serde_json = '1.0'
structopt = '0.3.8'

# Substrate dependencies
frame-benchmarking = '3.1.0'
frame-benchmarking-cli = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-basic-authorship = '0.9.0'
sc-chain-spec = '3.0.0'
sc-cli = { features = ['wasmtime'], version = '0.9.0' }
sc-client-api = '3.0.0'
sc-consensus = '0.9.0'
sc-consensus-babe = '0.9.0'
sc-executor = { features = ['wasmtime'], version = '0.9.0' }
sc-finality-grandpa = '0.9.0'
sc-keystore = '3.0.0'
sc-rpc = '3.0.0'
sc-rpc-api = '0.9.0'
sc-service = { features = ['wasmtime'], version = '0.9.0' }
sc-telemetry = '3.0.0'
sc-transaction-pool = '3.0.0'
sp-api = '3.0.0'
sp-block-builder = '3.0.0'
sp-blockchain = '3.0.0'
sp-consensus = '0.9.0'
sp-consensus-babe = '0.9.0'
sp-core = '3.0.0'
sp-finality-grandpa = '3.0.0'
sp-inherents = '3.0.0'
sp-runtime = '3.0.0'
sp-transaction-pool = '3.0.0'
substrate-frame-rpc-system = '3.0.0'

# Local dependencies
mv-node-runtime = { path = '../runtime', version = '3.0.0' }
sp-mvm-rpc = { path = '../pallets/sp-mvm/rpc' }
sp-mvm-rpc-runtime = { path = '../pallets/sp-mvm/rpc/runtime' }

[dependencies.move-vm]
package = "mvm"
git = "https://github.com/pontem-network/sp-move-vm.git"
rev = "e84b6eab01fb6e2520d86ba6a5fe9466404b12fe"
default-features = false
features = [ "move_stdlib" ]

[features]
default = []
runtime-benchmarks = ['mv-node-runtime/runtime-benchmarks']
