name: Extra
on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTUP_MAX_RETRIES: 10
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: "Coverage"
    runs-on: ${{ matrix.cfg.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        cfg:
          - os: self-hosted
            grcov:
              version: tags/v0.8.6
              file: grcov-v0.8.6-x86_64-unknown-linux-gnu.tar.gz
            dove: 1.5.5

    env:
      SKIP_WASM_BUILD: 1
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
      RUSTDOCFLAGS: "-Cpanic=abort"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: cargo clean
        run: cargo clean

      - name: get latest grcov binary
        uses: dsaltares/fetch-gh-release-asset@0.0.7
        with:
          repo: mozilla/grcov
          # TODO: use `version: "latest"` and wildcard in the `file`
          version: ${{ matrix.cfg.grcov.version }}
          file: ${{ matrix.cfg.grcov.file }}

      - name: unpack grcov release binary
        run: |
          tar -xvf ${{ matrix.cfg.grcov.file }}
          sudo chown runner ./grcov && chmod +x ./grcov
          cp grcov ~/.cargo/bin/grcov
          rm ${{ matrix.cfg.grcov.file }}

      - name: cache Dove
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ${{ matrix.cfg.os }}-dove-${{ matrix.cfg.dove }}

      - name: get Dove
        uses: pontem-network/get-dove@main
        with:
          prerelease: true
          version: ${{ matrix.cfg.dove }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test resources
        run: make assets

      - name: cargo build tests +profile
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p=sp-mvm --no-fail-fast -- --test-threads=1

      - id: coverage_html
        name: coverage analysis with grcov (html)
        uses: actions-rs/grcov@v0.1
        with:
          config: .github/grcov+html.yml
      - name: make report artifact
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report.html
          path: ${{ steps.coverage_html.outputs.report }}

      - id: coverage
        name: coverage analysis with grcov
        uses: actions-rs/grcov@v0.1
        with:
          config: .github/grcov.yml

      - name: make report artifact
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report.lcov
          path: ${{ steps.coverage.outputs.report }}

      - name: upload report to Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
