name: Tag Version
on:
  push:
    branches:
      - master
      - release-v?[0-9]+.[0-9]+**

jobs:
  push-tag:
    name: Tag crate version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: new_tag
        name: try create tag
        uses: pontem-network/tag-crate-version@main
        with:
          crate: pontem
          version-to-tag: "v$1"
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      crate: ${{ steps.new_tag.outputs.crate }}
      version: ${{ steps.new_tag.outputs.current }}
      tag: ${{ steps.new_tag.outputs.tag }}
      prev-tag: ${{ steps.new_tag.outputs.previous }}
      success: ${{ steps.new_tag.outputs.success }}

  release:
    needs: push-tag
    if: needs.push-tag.outputs.success
    uses: pontem-network/pontem/.github/workflows/release.yml@master
    # SHOULD BE uses: ${{ github.event.repository.full_name }}/.github/workflows/release.yml@${{ github.ref }} or ${{ needs.push-tag.outputs.tag }}
    with:
      tag: ${{ needs.push-tag.outputs.tag }}
